### ISSUE TITLE
Change Tag Name Destroy Indentation

### ISSUE THREAD

**Issue by weilbith** [tpope/vim-surround#254]
Hey! 
First I like to thank you for this great plugin. So simple but definitely one of the plugins I use most.
Unfortunately I get the following problem: If I rename a tag in e.g. `html`, the tag gets successfully renamed, but the indentation is destroyed afterwards. The following example should make this clear.
Assume I have this snippet of code:
```html
....
      <footer>
        <span class="icon"
              href="https://twitter.com">
          <i class="fa fa-twitter" />
        </span>
     </footer
....
```

When I'm in the `<span` tag and do now `cstta<cr>`, I get this:

```html
....
      <footer>
      <a class="icon"
      href="https://twitter.com">

      <i class="fa fa-twitter" />

      </a>
     </footer
....
```

As you can see, a bunch of things are getting wrong. Two new lines are added, the whole tag block is indented on the same level as the parent tag and all its child tags also. At least the tags option on the next line is also not correct, but I assume that has the same reason.
That makes this feature not usable for me. Instead I've to do it manually what sucks to be honest...
Thanks for reading!

**Comment by tpope** [comment]
You can try setting `g:surround_indent` but I'm not sure what's going on with the blank lines.

**Comment by matsuhav** [comment]
Probably because the tag is followed by `<CR>`, `cstta<CR>` sets
regtype 'V'(linewise) though its keeper("inner tag" part) doesn't end with `<CR>`.
And `setreg()` at line 452 adds extra `<CR>` to `@"`.  

For example, after the line 452, add this two lines. They differ after the command.
```
let @a=keeper
let @b=getreg('"')
```

This is the latter blank line.  Remove this extra `<CR>`.

And fixed not to add `<CR>` to `before` when `keeper` preceded by `<CR>` just line `after`.
This is the former blank line.

**Comment by lucasdellabella** [comment]
@matsuhav this change is working for you? Still having this issue.

**Comment by pexea12** [comment]
I am still having this issue

```
<QuickFadeOut>
 ..
.  <View>
    <Text>Hello</Text>
   </View>
 ....
</QuickFadeOut>
```

`cst<View>` and `Enter` on `QuickFadeOut` turns into
```
<View>
 ..
.  <View>
     <Text>Hello</Text>
       </View>
 ....
          </View>
```
