### ISSUE TITLE
Surround with '<'

### ISSUE THREAD

**Issue by invis87** [tpope/vim-surround#304]
I am rust developer and sometimes want to surround text with `<{text}>`, but plugin think that I want html tag. Can we add some config option, or keybinding to fix that?

**Comment by tpope** [comment]
`ysiw>`. This is documented.

**Comment by mohitgarg** [comment]
@tpope I tried the same with self closing jsx tag but it didn't work. For example:

`<TextField fullWidth label={'Example'} onChange={() => {}} />`

I want to surround this with `{` 
When I do `ysa<` or `ysa>` it ends up adding an extra curly brace after the onChange attribute

Current Behaviour
`{<TextField fullWidth label={'Example'} onChange={() => {}}} />`

Expected Behaviour
`{<TextField fullWidth label={'Example'} onChange={() => {}} />}`
