### ISSUE TITLE
Feature request: restore cursor position after doing surrounding

### ISSUE THREAD

**Issue by baopham** [tpope/vim-surround#55]
Just like issue #2 presents, after doing a surround command, the cursor always goes to the beginning of the operand text. 
It'd be more efficient if there's an option to keep the cursor where it was before . Is it possible?

**Comment by alexdunn** [comment]
@sunaku Thanks for the tip.  That's very helpful.  

I think this feature is vital in Objective-C where the programmer is constantly surrounding the current line in `[]`, expecting to continue typing after the `]`
```
// First I type:
NSString alloc yssr <cursor position>
// Which produces:
<cursor position> [NSString alloc]
// But this would be far more convenient and natural, as I'm going to be doing this 3 to 5+ times per line of code:
[NSString alloc] <cursor position>
```

If this were made an option to users of surround.vim, it's unclear to me why inconsistency with default vim behavior would even be a consideration.  Indeed, we're adding plugins to our vim because we aren't happy with the default behavior.

Either way, super duper thanks @tpope for this awesome plugin! :+1:
